# Generated by Django 4.0.10 on 2023-04-19 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(max_length=100, verbose_name='规则方案')),
                ('short_circuit', models.SmallIntegerField(default=0, verbose_name='短路')),
                ('blank_skip', models.SmallIntegerField(default=0, verbose_name='空值跳过')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('return_value', models.CharField(max_length=200, verbose_name='返回值')),
                ('flag_index', models.IntegerField(default=0, verbose_name='排序号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rule.case')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=100, verbose_name='字段')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('match_type', models.CharField(max_length=20, verbose_name='描述')),
                ('target_type', models.CharField(max_length=20, verbose_name='目标比对类型')),
                ('target_value', models.CharField(max_length=200, verbose_name='目标值')),
                ('flag_index', models.IntegerField(default=0, verbose_name='排序号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='rule.item')),
            ],
        ),
    ]
