# Generated by Django 4.0.10 on 2023-04-25 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='min_match_amount',
            field=models.IntegerField(default=0, verbose_name='最少匹配数'),
        ),
        migrations.AlterField(
            model_name='item',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rule.case'),
        ),
    ]
